# Generated by Django 3.2.4 on 2021-06-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0003_alter_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('items', models.ManyToManyField(blank=True, to='shop.Product')),
            ],
        ),
    ]
